"""Tag rules and negation handling.

Tags are generated by weighted lexicon matching over review/comment text rather
than by an LLM classifier. That is a deliberate choice for v1: the vocabulary is
small and closed (~25 tags), the rules are auditable ("we tagged this 'quiet'
because these three comments said so"), and it costs nothing per place. An LLM
would generalize better to tags nobody enumerated, at the cost of being
unexplainable, non-deterministic, and metered.

## Negation is the whole problem

Naive substring matching gets these exactly backwards, and all four appear
verbatim in real Madrid review text:

    "Tiny, no laptops, in and out."          -> NOT laptop-friendly
    "Loud, fun, not a place for a quiet dinner."  -> NOT quiet
    "Not a romantic dinner, more of an event."    -> NOT date-night
    "Nightlife, not a bar."                       -> NOT bar-like

So every match is checked against a NegEx-style lookback window: a match is
discarded if a negator appears within `NEGATION_WINDOW_TOKENS` before it and no
clause boundary intervenes. This is the same technique clinical NLP uses for
"no evidence of pneumonia", and it is far cheaper than a parser.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

#: Words that flip the polarity of a following phrase.
NEGATORS = frozenset(
    {
        "no", "not", "never", "none", "without", "isnt", "isn't", "arent",
        "aren't", "wasnt", "wasn't", "dont", "don't", "doesnt", "doesn't",
        "didnt", "didn't", "cant", "can't", "cannot", "wont", "won't",
        "hardly", "barely", "avoid", "skip", "lacks", "lacking", "anything",
        "far", "less",
    }
)

#: How many tokens before a match to scan for a negator. 6 rather than 3-4
#: because English puts real distance between the two — "not a place for a
#: quiet dinner" has five tokens between "not" and "quiet". A window this wide
#: is only safe because of the clause-boundary guard below; without it,
#: "It's not cheap, but the quiet terrace is lovely" would negate "quiet".
NEGATION_WINDOW_TOKENS = 6

#: Punctuation that ends a clause, blocking negation from reaching across it.
#: Without this, "It's quiet. No music." would negate "quiet".
_CLAUSE_BOUNDARY = frozenset(
    {".", "!", "?", ";", ":", "but", "however", "though", "although"}
)

_TOKEN_RE = re.compile(r"[\w']+|[.!?;:]")


@dataclass(frozen=True, slots=True)
class TagRule:
    """One tag and the evidence that triggers it.

    `min_evidence_share` is a fraction of a place's *weighted* evidence, not a
    raw count: one upvoted comment calling a place quiet outweighs three
    unvoted ones, and a place with fifty snippets should need more than a single
    stray mention.
    """

    tag: str
    include: tuple[str, ...]
    #: Phrases that veto the tag outright, regardless of include matches.
    exclude: tuple[str, ...] = ()
    min_evidence_share: float = 0.18
    #: Require at least this mean sentiment across matching snippets.
    min_sentiment: float | None = None
    description: str = ""


#: The closed tag vocabulary. Grouped by the filter axes the UI exposes:
#: company (who it suits), vibe, practical, and consensus.
TAG_RULES: tuple[TagRule, ...] = (
    # --- who it suits -------------------------------------------------------
    TagRule(
        "family-friendly",
        include=(
            "kids", "kid", "children", "child", "family", "with kids", "my kids",
            "7 year old",
        ),
        exclude=("not for kids", "no kids", "adults only", "not a place for kids"),
        description="Mentioned in the context of travelling with children.",
    ),
    TagRule(
        "solo-friendly",
        include=(
            "solo", "by myself", "on my own", "alone", "read for an hour",
            "laptop", "in and out", "at the counter", "standing at the counter",
        ),
        description="Comfortable to visit alone: counter seating, no minimum party.",
    ),
    TagRule(
        "group-friendly",
        include=(
            "group", "groups", "we were six", "party of", "with friends",
            "students", "squeezed us in",
        ),
        exclude=("not for a group", "no groups", "terrible for a date"),
        description="Works for four or more people.",
    ),
    TagRule(
        "date-night",
        include=("romantic", "date", "intimate", "candlelit", "unforgettable"),
        exclude=("not a romantic", "not romantic", "terrible for a date", "not a date"),
        min_sentiment=0.0,
        description="Suited to a couple.",
    ),
    # --- vibe ---------------------------------------------------------------
    TagRule(
        "quiet",
        include=(
            "quiet", "calm", "peaceful", "relaxed", "no music", "dim", "dark",
            "intimate", "have a conversation", "actually talk", "shaded",
            "unchanged", "atmospheric",
        ),
        exclude=("not quiet", "anything but quiet", "not a place for a quiet"),
        description="Low noise, conversation possible.",
    ),
    TagRule(
        "lively",
        include=(
            "lively", "loud", "buzzing", "packed", "rammed", "crowded",
            "chaotic", "standing room only", "dance", "deafening",
            "very young crowd", "queue", "bustling",
        ),
        description="Busy and noisy, in a good way or otherwise.",
    ),
    TagRule(
        "touristy",
        include=("tourist trap", "touristy", "tourists", "tourist"),
        exclude=("not a tourist", "not touristy", "not a tourist one"),
        description="Dominated by visitors rather than locals.",
    ),
    TagRule(
        "local-favorite",
        include=(
            "locals", "local crowd", "full of locals", "neighbourhood", "neighborhood",
            "where chefs eat", "institution", "not a tourist one", "locals use",
        ),
        description="Frequented by residents.",
    ),
    # --- practical ----------------------------------------------------------
    TagRule(
        "budget",
        include=(
            "cheap", "budget", "great value", "unbeatable value", "absurd value",
            "costs almost nothing", "free", "inexpensive", "reasonable",
            "good value", "free entry",
        ),
        exclude=("not cheap", "far from cheap", "not free"),
        description="Notably inexpensive for what it offers.",
    ),
    TagRule(
        "pricey",
        include=("expensive", "overpriced", "pricey", "not cheap", "splurge", "eye-watering"),
        description="Costs more than the category norm.",
    ),
    TagRule(
        "laptop-friendly",
        include=("laptop friendly", "laptop", "plugs", "wifi", "work here", "worked here"),
        # The critical veto: "Tiny, no laptops, in and out." is the opposite claim.
        exclude=("no laptops", "not laptop", "no wifi", "laptops are not"),
        min_evidence_share=0.12,
        description="Practical for working or lingering.",
    ),
    TagRule(
        "reservation-recommended",
        include=(
            "book ahead", "book weeks ahead", "reservation", "reserve", "booking",
            "book the", "will not get in", "won't get in", "sought-after",
        ),
        min_evidence_share=0.12,
        description="Walk-ins are unlikely to get a table.",
    ),
    TagRule(
        "queue-likely",
        include=("queue", "line", "wait", "waiting", "get there before", "before the rush"),
        min_evidence_share=0.12,
        description="Expect to wait.",
    ),
    TagRule(
        "cash-only",
        include=("cash only", "cash when", "no cards", "does not take cards"),
        min_evidence_share=0.08,
        description="Bring cash.",
    ),
    TagRule(
        "outdoor-seating",
        include=("terrace", "outdoor", "outside seating", "patio", "on the street"),
        min_evidence_share=0.12,
        description="Has a terrace or outdoor tables.",
    ),
    TagRule(
        "late-night",
        include=(
            "late night", "until 6am", "until 6", "2am", "3am", "all night",
            "after a night out",
        ),
        min_evidence_share=0.10,
        description="Open unusually late.",
    ),
    # --- consensus ----------------------------------------------------------
    TagRule(
        "hidden-gem",
        include=(
            "hidden gem", "nobody knows", "almost nobody", "underrated",
            "not on any blog", "hardly anyone", "never crowded",
        ),
        min_evidence_share=0.10,
        min_sentiment=0.0,
        description="Well-regarded but little-known.",
    ),
    TagRule(
        "overrated",
        include=("overrated", "overhyped", "not worth", "disappointing", "underwhelming"),
        min_evidence_share=0.10,
        description="Reputation exceeds the experience, per reviewers.",
    ),
)


# --- matching ---------------------------------------------------------------


def _tokenize(text: str) -> list[str]:
    return _TOKEN_RE.findall(text.lower())


def _is_negated(tokens: list[str], match_index: int) -> bool:
    """Whether a negator precedes `match_index` within the lookback window,
    with no clause boundary in between."""
    start = max(0, match_index - NEGATION_WINDOW_TOKENS)
    for token in reversed(tokens[start:match_index]):
        if token in _CLAUSE_BOUNDARY:
            return False
        if token in NEGATORS:
            return True
    return False


def phrase_hits(text: str, phrase: str) -> int:
    """Count non-negated occurrences of `phrase` in `text`.

    Matching is token-based rather than substring-based so "line" does not match
    "online" and "date" does not match "update".
    """
    tokens = _tokenize(text)
    needle = _tokenize(phrase)
    if not needle:
        return 0
    hits = 0
    for i in range(len(tokens) - len(needle) + 1):
        if tokens[i : i + len(needle)] != needle:
            continue
        if _is_negated(tokens, i):
            continue
        hits += 1
    return hits


def matches_any(text: str, phrases: tuple[str, ...]) -> bool:
    """True if any phrase occurs, ignoring negation (used for vetoes).

    Vetoes match literally: the phrase "no laptops" *is* the negation, so
    running it through the negation filter would cancel it out.
    """
    tokens = _tokenize(text)
    for phrase in phrases:
        needle = _tokenize(phrase)
        if not needle:
            continue
        for i in range(len(tokens) - len(needle) + 1):
            if tokens[i : i + len(needle)] == needle:
                return True
    return False


@dataclass(slots=True)
class TagEvidence:
    """Why a tag was applied, for auditing and for the UI."""

    tag: str
    share: float
    matched_phrases: list[str] = field(default_factory=list)
    sample_snippets: list[str] = field(default_factory=list)
